annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: vSphere CSI
  catalog.cattle.io/kube-version: '>= 1.20.0-0 < 1.29.0-0'
  catalog.cattle.io/namespace: kube-system
  catalog.cattle.io/os: linux,windows
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/rancher-version: '>= 2.8.0-0'
  catalog.cattle.io/release-name: vsphere-csi
apiVersion: v1
appVersion: 3.0.3-rancher2
description: vSphere Cloud Storage Interface (CSI)
icon: https://charts.rancher.io/assets/logos/vsphere-csi.svg
keywords:
- infrastructure
maintainers:
- email: jiaqi.luo@suse.com
  name: Jiaqi Luo
- email: anna.blendermann@suse.com
  name: Andy Blendermann
- email: brad.davidson@suse.com
  name: Brad Davidson
name: rancher-vsphere-csi
sources:
- https://github.com/kubernetes-sigs/vsphere-csi-driver
version: 3.0.3-rancher1
