name: CI on Pull Request

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1 https://github.com/actions/checkout/tags
      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0 https://github.com/actions/setup-go/tags
        with:
          go-version-file: go.mod
      - name: Install Helm
        run: |
          set -euo pipefail

          HELM_VERSION="v3.20.1"
          HELM_TARBALL="helm-${HELM_VERSION}-linux-amd64.tar.gz"
          HELM_SHA256="0165ee4a2db012cc657381001e593e981f42aa5707acdd50658326790c9d0dc3"

          curl -fsSLO "https://get.helm.sh/${HELM_TARBALL}"

          echo "${HELM_SHA256}  ${HELM_TARBALL}" | sha256sum -c -

          tar -xzf "${HELM_TARBALL}"
          sudo mv linux-amd64/helm /usr/local/bin/helm
          helm version --short
      - name: Run CI
        run: make
